# PLACE HOLDER UNTIL FULL MAKE FILE IS DONE

CC = gcc
CFLAGS = -Wall -pedantic -Wextra -std=gnu90

all: mytestlist

mytestlistL mytestlist.c list_adders.c list_movers.c list_removers.c 
    $(CC) $(CFLAGS) -o mytestlist mytestlist.c list_adders.c list_movers.c list_removers.c 


clean:
    rm -f mytestlist