#NAME: Javier Andres Tarazona Jimenez, Nahian Sajid 
#NSID: elr490, Zas742
#Student Number: 11411898, 11309563

# PLACE HOLDER UNTIL FULL MAKE FILE IS DONE

CC = gcc -g
CFLAGS = -Wall -pedantic -Wextra -std=gnu90

all: mytestlist

mytestlistL mytestlist.c list_adders.c list_movers.c list_removers.c 
    $(CC) $(CFLAGS) -o mytestlist mytestlist.c list_adders.c list_movers.c list_removers.c 


clean:
    rm -rf mytestlist
